import type { Metadata } from "next";
import {Montserrat} from "next/font/google";
import "./globals.css";
import { getServerSession} from "next-auth";
import SessionProvider from "@/components/SessionProvider";
import {redirect} from "next/navigation";

const montserrat = Montserrat({
    variable: "--font-montserrat",
    subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} font-sans antialiased`}
      >
      <SessionProvider session={session}>
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
